project:
  type: website
  output-dir: docs

website:
  title: "Suppapat Korsurat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full
    
editor: visual

